version: '3.4'

volumes:
  mysql_data:
    driver: local
  realm-export.json:

services:
  keycloak:
    container_name: keycloak
    hostname: keycloak
    image: localhost/keycloak/keycloak:latest
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    volumes:
      - ${PWD}/realm-export.json:/opt/keycloak/data/import/realm-export.json
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    restart: on-failure
    command:
      - start-dev
      - --import-realm
      - --http-relative-path=/auth
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOSTNAME}:8080/auth"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s
  rdpgw:
    container_name: rdpgw
    hostname: rdpgw
    image: ghcr.io/gmarcy/rdpgw:latest
    build: .
    ports:
      - 9443:9443
    restart: on-failure
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      RDPGW_SERVER__SESSION_STORE: file
      RDPGW_SERVER__CERT_FILE: /opt/rdpgw/server.pem
      RDPGW_SERVER__KEY_FILE: /opt/rdpgw/key.pem
      RDPGW_SERVER__GATEWAY_ADDRESS: ${HOSTNAME}:9443
      RDPGW_SERVER__PORT: 9443
      RDPGW_SERVER__HOSTS: "any"
      RDPGW_SERVER__HOST_SELECTION: "any"
      RDPGW_SERVER__ROUND_ROBIN: "false"
      RDPGW_OPEN_ID__PROVIDER_URL: "http://${HOSTNAME}:8080/auth/realms/rdpgw"
      RDPGW_OPEN_ID__CLIENT_ID: rdpgw
      RDPGW_OPEN_ID__CLIENT_SECRET: 01cd304c-6f43-4480-9479-618eb6fd578f
      RDPGW_CLIENT__NO_USERNAME: true
      RDPGW_CAPS__TOKEN_AUTH: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOSTNAME}:8080"]
      interval: 10s
      timeout: 10s
      retries: 10
