version: '3.4'

volumes:
  mysql_data:
      driver: local
  realm-export.json:

services:
  keycloak:
    container_name: keycloak
    image: richardjkendall/keycloak-arm:latest
    hostname: keycloak
    volumes:
      - ${PWD}/realm-export.json:/export/realm-export.json
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /export/realm-export.json
    ports:
      - 8080:8080
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s
  xrdp:
    container_name: xrdp
    hostname: xrdp
    image: ghcr.io/gmarcy/docker-ubuntu-xrdp-mate-rdpgw:latest
    ports:
      - 3389:3389
    restart: on-failure
    volumes:
      - ${PWD}/xrdp_users.txt:/root/createusers.txt
    environment:
      TZ: "Europe/Amsterdam"
  rdpgw:
    container_name: rdpgw
    hostname: rdpgw
    image: ghcr.io/gmarcy/rdpgw:latest
    build: .
    ports:
      - 9443:9443
    restart: on-failure
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      RDPGW_SERVER__SESSION_STORE: file
      RDPGW_SERVER__CERT_FILE: /opt/rdpgw/server.pem
      RDPGW_SERVER__KEY_FILE: /opt/rdpgw/key.pem
      RDPGW_SERVER__GATEWAY_ADDRESS: localhost:9443
      RDPGW_SERVER__PORT: 9443
      RDPGW_SERVER__HOSTS: xrdp:3389
      RDPGW_SERVER__ROUND_ROBIN: "false"
      RDPGW_OPEN_ID__PROVIDER_URL: "http://keycloak:8080/auth/realms/rdpgw"
      RDPGW_OPEN_ID__CLIENT_ID: rdpgw
      RDPGW_OPEN_ID__CLIENT_SECRET: 01cd304c-6f43-4480-9479-618eb6fd578f
      RDPGW_CLIENT__USERNAME_TEMPLATE: "{{ username }}"
      RDPGW_CAPS__TOKEN_AUTH: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://keycloak:8080"]
      interval: 10s
      timeout: 10s
      retries: 10
